name: 'Cloudways API Git Pull'
description: 'Github Action to deploy your project to Cloudways.'
branding:
  icon: 'arrow-up-right'
  color: 'blue'
inputs:
  email:
    description: 'Cloudways Account Email'
    required: true
  api-key:
    description: 'Cloudways API Key'
    required: true
  server-id:
    description: 'Cloudways Server ID'
    required: true
  app-id:
    description: 'Cloudways App ID'
    required: true
  branch-name:
    description: 'The Git branch you are pulling the changes'
    required: true
  deploy-path:
    description: 'The path you are deploying the changes (ignore public_html string)'
    required: true
    default: ''
outputs:
  operation:
    description: 'The Cloudways API operation ID'
runs:
  using: 'node16'
  main: 'dist/index.js'
